export const PageIDs = {
  Home: 1,
  TourListing: 2,
  TourListingDetails: 3,
  MICETours: 4,
  MICEDestinationWeddings: 5,
  MICEMeetings: 6,
  Accomodation: 7,
  Destinations: 8,
  DestinationDetails: 9,
  AboutUs: 10,
  ContactUs: 11,
  Blogs: 12,
  BlogsArticle: 13,
  ExperianceDetails: 14,
  TravelDesk: 15,
  TourPlanner_1: 16,
  TourPlanner_2: 17,
  TourPlanner_3: 18,
  TourPlanner_4: 19,
  TourPlanner_5: 20,
  TourPlanner_6: 21,
  TourPlanner_7: 22,
  TourPlanner_8: 23,
  TourReview: 24,
};
