// export const PageIDs = {
//   Home: 1,
//   TourListing: 2,
//   TourListingDetails: 3,
//   MICETours: 4,
//   MICEDestinationWeddings: 5,
//   MICEMeetings: 6,
//   Accomodation: 7,
//   Destinations: 8,
//   DestinationDetails: 9,
//   AboutUs: 10,
//   ContactUs: 11,
//   Blogs: 12,
//   BlogsArticle: 13,
//   ExperianceDetails: 14,
//   TravelDesk: 15,
//   TourPlanner_1: 16,
//   TourPlanner_2: 17,
//   TourPlanner_3: 18,
//   TourPlanner_4: 19,
//   TourPlanner_5: 20,
//   TourPlanner_6: 21,
//   TourPlanner_7: 22,
//   TourPlanner_8: 23,
//   TourReview: 24,
// };

export const PageIDs = {
  Home: 1,
  TourListing: 2,
  TourListingDetails: 3,
  MICETours: 21,
  MICEDestinationWeddings: 22,
  MICEMeetings: 23,
  Accomodation: 7,
  Destinations: 18,
  DestinationDetails: 19,
  AboutUs: 20,
  ContactUs: 12,
  Blogs: 24,
  BlogsArticle: 25,
  ExperianceDetails: 26,
  TravelDesk: 27,
  TourPlanner_1: 28,
  TourPlanner_2: 29,
  TourPlanner_3: 30,
  TourPlanner_4: 31,
  TourPlanner_5: 32,
  TourPlanner_6: 33,
  TourPlanner_7: 34,
  TourPlanner_8: 35,
  TourReview: 36,
};
